# Generated by Django 3.0.8 on 2020-08-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('title', models.CharField(default='no title', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('question_text', models.TextField(max_length=300, verbose_name='question_text')),
                ('answer_text', models.TextField(max_length=300, verbose_name='answer_text')),
                ('answer_audio', models.FileField(blank=True, upload_to='answer_audio/', verbose_name='answer_audio')),
                ('category', models.CharField(default='no category', max_length=200, verbose_name='category')),
                ('subcategory', models.CharField(default='no subcategory', max_length=200, verbose_name='subcategory')),
                ('detail', models.CharField(default='no detail', max_length=200, verbose_name='detail')),
                ('literary_style', models.BooleanField(default=False, verbose_name='literary_style')),
                ('proficiency_score', models.FloatField(default=0.0, verbose_name='proficiency_score')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='attempt_count')),
                ('last_trial_date', models.DateTimeField(auto_now_add=True, verbose_name='last_trial_date')),
                ('card_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
    ]
